# ref: https://bun.sh/docs/runtime/bunfig
[install]
auto = "force"

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true

[test]
coverage = true
coverageThreshold = { line = 0.7, function = 0.8, statement = 0.9 }

[serve.static]
plugins = ["bun-plugin-tailwind"]
